dependencies:
  - OpenZeppelin/openzeppelin-contracts@4.8.3

compiler:
  solc:
    version: 0.8.19
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - '@openzeppelin/contracts=OpenZeppelin/openzeppelin-contracts@4.8.3/contracts'
